# numpy

### Numpy ndarray

* 기본 python 에서는 배열이 없음
* numpy 의 ndarray 를 사용함
* ndarrray 생성하기 : numpy 의 array() 함수를 사용해서 생성 함

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print(type(list1))
print(list1)

<class 'list'>
[1, 2, 3]


In [3]:
list1 = np.array(list1)
print(type(list1))
print(list1)

<class 'numpy.ndarray'>
[1 2 3]


### ndarray 의 shape 와 차원

In [4]:
array1 = np.array([1, 2, 3])
print(type(array1), array1.shape)
print(array1)

<class 'numpy.ndarray'> (3,)
[1 2 3]


In [5]:
array2 = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                  ])
print(type(array2), array2.shape)
print(array2)

<class 'numpy.ndarray'> (2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
array3 = np.array([
                    [1, 2, 3]
                  ])
print(type(array3), array3.shape)
print(array3)

<class 'numpy.ndarray'> (1, 3)
[[1 2 3]]


### ndarray 의 ndim 속성 : 몇 차원인지 알려줌

In [7]:
print(f"array1 : {array1.ndim} 차원\n"
      f"array2 : {array2.ndim} 차원\n"
      f"array3 : {array3.ndim} 차원\n")

array1 : 1 차원
array2 : 2 차원
array3 : 2 차원



### dtype : 배열 속에 들어있는 data 의 type 을 알려줌

In [8]:
array1 = np.array([1, 2, 3])
print("array1의 dtype :", array1.dtype)

# <U11 : 문자열을 의미함
array2 = np.array([1, 2, '3'])
print("array2의 dtype :", array2.dtype)

array3 = np.array([1, 2, 3.0])
print("array3의 dtype :", array3.dtype)

array1의 dtype : int64
array2의 dtype : <U21
array3의 dtype : float64


### astype() : dtype을 반환함

In [9]:
array_int = np.array([1, 2, 3])
print(array_int.dtype, array_int)

array_float = array_int.astype('float64')
print(array_float.dtype, array_float)

array_int2 = array_float.astype('int32')
print(array_int2.dtype, array_int2)

array_float2 = np.array([1., 2., 3.])
print(array_float2.dtype, array_float2)

array_float2 = np.array([1.0, 2.0, 3.0])
print(array_float2.dtype, array_float2)

array_int3 = array_float2.astype('int32')
print(array_int3.dtype, array_int3)

int64 [1 2 3]
float64 [1. 2. 3.]
int32 [1 2 3]
float64 [1. 2. 3.]
float64 [1. 2. 3.]
int32 [1 2 3]


### ndarray 연산 : axis 기반

* axis=0 : 열끼리 연산함
* axis=1 : 행 안에 있는 요소들끼리 연산함

In [10]:
array2 = np.array([
                    [1, 2, 3],
                    [4, 5, 6],
                 ])

print(array2.ndim, '차원')
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

2 차원
21
[5 7 9]
[ 6 15]


### ndarray : arange, zeros, ones

In [11]:
squence_array = np.arange(10)

print(type(squence_array), squence_array.dtype)
print(squence_array)

<class 'numpy.ndarray'> int64
[0 1 2 3 4 5 6 7 8 9]


In [12]:
zero_array = np.zeros((3, 2), dtype='int32')

print(type(zero_array), zero_array.dtype)
print(zero_array)

<class 'numpy.ndarray'> int32
[[0 0]
 [0 0]
 [0 0]]


In [13]:
one_array = np.ones((3, 2), dtype='int32')

print(type(one_array), one_array.dtype)
print(one_array)

<class 'numpy.ndarray'> int32
[[1 1]
 [1 1]
 [1 1]]


### ndarray 의 shape 변형하기 : reshape()

In [14]:
array1 = np.arange(10)
print(array1)
print()

array2 = array1.reshape(2, 5)
print(array2)
print()

array3 = array1.reshape(5, 2)
print(array3)

# 행과 열의 크기를 data 개수에 맞게 지정해야 함
# ValueError: cannot reshape array of size 10 into shape (3,3)
# array4 = array1.reshape(3, 3)
# print(array4)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### reshape() 메소드에 -1 을 넣어서 반환하기

* 행의 크기를 고정하고 열의 크기는 자동으로 결정되게 하기
* 열의 크기를 고정하고 행의 크기는 자동으로 결정되게 하기

In [15]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# 열의 크기를 5로 고정하고 행의 크기는 이에 맞추어서 결정됨
array2 = array1.reshape(-1, 5)
print(array1.ndim, array1.shape)
print(array2)

1 (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
# 행의 크기를 5로 고정하고 열의 크기는 이에 맞추어서 결정됨
array3 = array1.reshape(5, -1)
print(array1.ndim, array1.shape)
print(array3)

1 (10,)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array1 = np.arange(5)
print(array1.ndim, array1.shape)
print(array1)

1 (5,)
[0 1 2 3 4]


In [19]:
# 1차원 ndarray -> 2차원 ndarray
# 열 axis 의 크기는 1로 함
array2d = array1.reshape(-1, 1)

print(array2d.ndim, array2d.shape)
print(array2d)

2 (5, 1)
[[0]
 [1]
 [2]
 [3]
 [4]]


In [20]:
# 2차원 ndarray -> 1차원 ndarray
array1d = array2d.reshape(-1,)
print(array1d.ndim, array1d.shape)
print(array1d)

1 (5,)
[0 1 2 3 4]


In [21]:
# reshape()에 -1 은 열에 지정하든지, 행에 지정하든지 
# 한 군데에만 지정할 수 있음

# ValueError: can only specify one unknown dimension
# array1.reshape(-1, -1)

### ndarray 에서 data set 선택하기 : indexing

* 특정 위치에 있는 값 추출하기

In [22]:
array1 = np.arange(1, 10)
print(array1.ndim, array1.shape)
print(array1)

value = array1[2]
print(type(value), value)

value = array1[-1]
print(type(value), value)

value = array1[-2]
print(type(value), value)

array1[8] = 0
array1[0] = 9
print(array1)

1 (9,)
[1 2 3 4 5 6 7 8 9]
<class 'numpy.int64'> 3
<class 'numpy.int64'> 9
<class 'numpy.int64'> 8
[9 2 3 4 5 6 7 8 0]


In [23]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d.ndim, array2d.shape)
print(array2d)

2 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print('[0,0] :', array2d[0,0])
print('[0,1] :', array2d[0,1])
print('[1,0] :', array2d[1,0])
print('[2,2] :', array2d[2,2])

[0,0] : 1
[0,1] : 2
[1,0] : 4
[2,2] : 9


### Slicing

In [25]:
array1 = np.arange(1, 10)
print(array1.ndim, array1.shape)
print(array1)
print()

array2 = array1[0:3]
print(array2.ndim, array2.shape)
print(array2)
print()

array3 = array1[3:]
print(array3.ndim, array3.shape)
print(array3)
print()

array4 = array1[:]
print(array4.ndim, array4.shape)
print(array4)

1 (9,)
[1 2 3 4 5 6 7 8 9]

1 (3,)
[1 2 3]

1 (6,)
[4 5 6 7 8 9]

1 (9,)
[1 2 3 4 5 6 7 8 9]


In [26]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d.ndim, array2d.shape)
print(array2d)
print()

print('array2d[0:2,0:2] :', array2d[0:2,0:2], sep='\n')
print('array2d[1:3,0:3] :', array2d[1:3,0:3], sep='\n')
print('array2d[1:3,:] :', array2d[1:3,:], sep='\n')
print('array2d[:,:] :', array2d[:,:], sep='\n')
print('array2d[:2,1:] :', array2d[:2,1:], sep='\n')
print('array2d[:2,0] :', array2d[:2,0], sep='\n')

2 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2,0:2] :
[[1 2]
 [4 5]]
array2d[1:3,0:3] :
[[4 5 6]
 [7 8 9]]
array2d[1:3,:] :
[[4 5 6]
 [7 8 9]]
array2d[:,:] :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] :
[[2 3]
 [5 6]]
array2d[:2,0] :
[1 4]


In [27]:
# arrayed = np.arange([[1,2,3],[4,5,6],[7,8,9]])
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

print(array2d.ndim, array2d.shape)
print(array2d)
print()

2 (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [28]:
# 1 행 2 열 : [0,1]
print(array2d[0,1])

2


In [29]:
# 2열
print(array2d[:,1])

[2 5 8]


In [30]:
# 3행 2열
print(array2d[2:,1])

[8]


In [31]:
# 두번째 열의 첫 번째 부터 두 번째까지
print(array2d[:2,1])

[2 5]


In [32]:
# 세 번째 행에서 첫 번째 세 번째 요서
print(array2d[2, [0,2]]) # [7 9]

[7 9]


In [33]:
print(array2d > 3)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [34]:
print(array2d[array2d > 3])

[4 5 6 7 8 9]


In [35]:
array2d[1,1] = 555
print(array2d)

[[  1   2   3]
 [  4 555   6]
 [  7   8   9]]


In [36]:
print(array2d)

# 속도가 빠름
print(array2d[1,1])

# 속도가 느림
print(array2d[1][1])

[[  1   2   3]
 [  4 555   6]
 [  7   8   9]]
555
555


In [37]:
%%time
print(array2d)
print(array2d[2, 1:3])

[[  1   2   3]
 [  4 555   6]
 [  7   8   9]]
[8 9]
CPU times: user 444 µs, sys: 63 µs, total: 507 µs
Wall time: 489 µs


In [38]:
%%time
print(array2d)
print(array2d[2][1:3])

[[  1   2   3]
 [  4 555   6]
 [  7   8   9]]
[8 9]
CPU times: user 537 µs, sys: 109 µs, total: 646 µs
Wall time: 621 µs


### tolist() : ndarray 를 list 로 반환 함

In [39]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

print(array2d)
print()

array3 = array2d[[0,1],2]
print(array3.ndim, '차원')
print(array3)
print('tolist() :', array3.tolist())
print()

array4 = array2d[[0,2], 0:2]
print(array4.ndim, '차원')
print(array4)
print('tolist() :', array4.tolist())
print()

array5 = array2d[[0,1]]
print(array5.ndim, '차원')
print(array5)
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

1 차원
[3 6]
tolist() : [3, 6]

2 차원
[[1 2]
 [7 8]]
tolist() : [[1, 2], [7, 8]]

2 차원
[[1 2 3]
 [4 5 6]]



### Boolean Indexing

In [40]:
array1d = np.arange(1, 10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [41]:
print(array1d > 5)

[False False False False False  True  True  True  True]


In [42]:
result = array1d > 5
print(type(result))
print(result)

<class 'numpy.ndarray'>
[False False False False False  True  True  True  True]


In [43]:
print(array1d[array1d > 5])

[6 7 8 9]


In [44]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
print(array1d[boolean_indexes])

[6 7 8 9]


In [45]:
# array1d 의 index 로 이루어진 list 생성하기
#  ㄴ 이것을 ndarray 로 변환하기 (np.array())
array_indexes = np.array([5, 6, 7 ,8])
array1d[array_indexes]

array_indexes2 = np.array([3, 4, 5, 6])
array1d[array_indexes2]

array([4, 5, 6, 7])

In [46]:
array1d = np.arange(1, 10)
print(array1d)

list_boolean_filtering = []
for i in range(0, 9):
    if array1d[i] > 5:
        list_boolean_filtering.append(i)
print(list_boolean_filtering)

array_boolean_filtering = np.array(list_boolean_filtering)
print(array1d[array_boolean_filtering])

[1 2 3 4 5 6 7 8 9]
[5, 6, 7, 8]
[6 7 8 9]


### 행렬정렬

In [47]:
# np.sort() 로 정렬하기
origin_array = np.array([3, 1, 5, 9])
sort_array = np.sort(origin_array)
print('원본이 변형되지 않음')
print('원본 :', origin_array)
print('정렬 :', sort_array)

원본이 변형되지 않음
원본 : [3 1 5 9]
정렬 : [1 3 5 9]


In [48]:
origin_array = np.array([3, 1, 5, 9])

# ndarray.argsort() : 원본행렬을 정렬해서 원본요소의 index 를 출력함
argsort_array = origin_array.argsort()
print('origin_array(원본행렬의) 의 index 번호가 출력됨')
print(argsort_array)
print(origin_array)
print()

'''
원본행렬 :
  [3 1 5 9]
sort_array(정렬된 행렬):
  [1 3 5 9]
argsort_array :
  [1 0 2 3]
'''

sort_argort_array = np.sort(argsort_array)
print(sort_argort_array)
print(argsort_array)
print()

# ndarray 의 sort() 메소드
# 원본 자체를 정렬하고 새로운 ndarray를 생성(반환)하지 않음
sort_array2 = origin_array.sort()
print(sort_array2)
print(argsort_array)

origin_array(원본행렬의) 의 index 번호가 출력됨
[1 0 2 3]
[3 1 5 9]

[0 1 2 3]
[1 0 2 3]

None
[1 0 2 3]


In [49]:
origin_array = np.array([3, 1, 5, 9])
sort_array = np.sort(origin_array)

print('정렬 전 원본 :', origin_array)
print('정렬 :', sort_array)
print('정렬 후 원본 :', origin_array)

정렬 전 원본 : [3 1 5 9]
정렬 : [1 3 5 9]
정렬 후 원본 : [3 1 5 9]


In [50]:
'''
원본 :                  [3 1 5 9]
원본의 index :           [0 1 2 3]
정렬 :                  [1 3 5 9]
정렬되기 전의 원본의 인덱스 : [1 0 2 3]
sort_indexes :
 [1 0 2 3] <-- [1, 3, 5, 9] 정렬되기 전의 index가 정렬된 상태로 배치됨
'''
origin_array = np.array([3, 1, 5, 9])
sort_indexes = np.argsort(origin_array)

# 원본행렬의 요소들이 정렬되지는 않고 정렬된 원소들의 index 가 배치됨
print('정렬 전 원본 :', origin_array)
print('정렬 :', origin_array[sort_indexes])
print('정렬 후 원본 :', origin_array)

정렬 전 원본 : [3 1 5 9]
정렬 : [1 3 5 9]
정렬 후 원본 : [3 1 5 9]


### slicing (step) [::-1] 을 활용해서 np.sort() 함수로 내림차순 정렬하기

In [51]:
origin_array = np.array([3, 1, 5, 9])
sort_array_descending = np.sort(origin_array)[::-1]
print('원본행렬이 변형되지 않음')
print(sort_array_descending)
print(origin_array)

원본행렬이 변형되지 않음
[9 5 3 1]
[3 1 5 9]


In [52]:
# 원본 요소들을 내림차순으로 정렬하기 - [9 5 3 1]
origin_array = np.array([3, 1, 5, 9])
sort_array_descending = np.sort(origin_array)[::-1]
print(sort_array_descending)
print(origin_array)
print()

# 정렬된 상태의 요소들의 (정렬되기 전의) index 들이 배치됨
sort_indexes_descending = np.argsort(origin_array)[::-1]
print(sort_indexes_descending)
print(origin_array)

[9 5 3 1]
[3 1 5 9]

[3 2 0 1]
[3 1 5 9]


### 행(row) 방향으로 정렬하기 / 열(column) 방향으로 정렬하기

In [53]:
array2d = np.array([
    [8, 12],
    [7, 1]
])

print(array2d)
print('sum :', array2d.sum())
print()

print('-- axis=0 : 축이 행 - row 방향으로 정렬하기 -')
row_array2d = np.sort(array2d, axis=0)
print(row_array2d)
print('sum :', row_array2d.sum(axis=0))
print()

print('-- axis=1 : 축이 열 - column 방향으로 정렬하기 -')
row_array2d = np.sort(array2d, axis=1)
print(row_array2d)
print('sum :', row_array2d.sum(axis=1))
print()

[[ 8 12]
 [ 7  1]]
sum : 28

-- axis=0 : 축이 행 - row 방향으로 정렬하기 -
[[ 7  1]
 [ 8 12]]
sum : [15 13]

-- axis=1 : 축이 열 - column 방향으로 정렬하기 -
[[ 8 12]
 [ 1  7]]
sum : [20  8]



### key-value 형태의 data를 ndarray 로 생성하고 argsort()를 호출해서 key 값 정렬하기

이순신=80, 강감찬=76, 안중근=92, 유관순=56, 장보고=70

In [54]:
name_array = np.array(['이순신', '강감찬', '안중근', '유관순', '장보고'])
weight_array = np.array([80, 76, 92, 56, 70])

print(name_array)
print(weight_array)
print()

# weight_array 의 정렬된 값에 해당하는 원본 행렬 위치 index 를 잔환하고
# 이것을 사용해서 name_array 에서 name 값 추출하기
sort_indexes_weight = np.argsort(weight_array)

print('몸무게의 오름차순 순으로 이름 정렬하기')
sort_name_by_weight = name_array[sort_indexes_weight]
print('몸무게의 오름차순 순으로 정렬된 이름 :')
print(sort_name_by_weight)
print()

print('몸무게의 오름차순 순으로 몸무게 정렬하기')
sort_weight_by_weight = weight_array[sort_indexes_weight]
print('몸무게의 오름차순 순으로 정렬된 몸무게 :')
print(sort_weight_by_weight)

['이순신' '강감찬' '안중근' '유관순' '장보고']
[80 76 92 56 70]

몸무게의 오름차순 순으로 이름 정렬하기
몸무게의 오름차순 순으로 정렬된 이름 :
['유관순' '장보고' '강감찬' '이순신' '안중근']

몸무게의 오름차순 순으로 몸무게 정렬하기
몸무게의 오름차순 순으로 정렬된 몸무게 :
[56 70 76 80 92]


### 행렬의 내적(합)과 전치행렬

* 행렬의 내적(합)

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

print(A)
print()

print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]


In [56]:
'''
행렬의 내적(합) : np.dot() 함수 사용

[1 2 3] [7 8]
[4 5 6] [9 10]
        [11 12]
'''
product_array = np.dot(A, B)
print(product_array)

[[ 58  64]
 [139 154]]


In [57]:
'''
전치 행렬 : np.transpose() 함수 사용

[2 3]
[5 0] [2 5 1]
[1 1] [3 0 1]

[1 2 3] [1 4 7]
[4 5 6] [2 5 8]
[7 8 9] [3 6 9]

[1 2] [1 3 5]
[3 4] [2 4 6]
[5 6]
'''
C = np.array([
    [2, 3],
    [5, 0],
    [1, 1]
])
transpose_matrix1 = np.transpose(C)
print(transpose_matrix1)
print()

[[2 5 1]
 [3 0 1]]



In [58]:
D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
product_array = np.transpose(D)
print(product_array)
print()

[[1 4 7]
 [2 5 8]
 [3 6 9]]



In [59]:
E = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
product_array = np.transpose(E)
print(product_array)

[[1 3 5]
 [2 4 6]]
