### Numpy ndarray
* 기본 python 에서는 배열이 없음
* numpy 의 ndarray 를 사용함
* ndarray 생성하기 : numpy 이 array() 함수를 사용해서 생성함

In [ ]:
import numpy as np

In [ ]:
list1 = [1, 2, 3]
print("list1 :",list1)
print("list1 :",type(list1))

In [ ]:
array1 = np.array(list1)
print("array1 :",array1)
print("array1 :",type(array1))

### ndarray 의 shape 와 차원

In [ ]:
array1 = np.array([1, 2, 3])
print("array1 :",array1)
print("array1 :",type(array1))
print("array1 :",array1.shape)

In [ ]:
array2 = np.array([
                    [1, 2, 3], 
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]
                  ])
print("array2 :",array2)
print("array2 :",type(array2))
print("array2 :",array2.shape)

In [ ]:
array3 = np.array([
                    [1, 2, 3]                   
                  ])
print("array3 :",array3)
print("array3 :",type(array3))
print("array3 :",array3.shape)

### ndarray 의 ndim 속성 : 몇 차원인지 알려줌

In [ ]:
print(f"array1 : {array1.ndim} 차원\n"
      f"array2 : {array2.ndim} 차원\n"
      f"array3 : {array3.ndim} 차원\n")

### dtype : 배열 속에 들어있는 data 의 type을 알려줌

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, "3"])
array3 = np.array([1, 2, 3.0])
print("array1의 dtype :",array1.dtype)
# <U11 : 문자열을 의미함
print("array2의 dtype :",array2.dtype)
print("array3의 dtype :",array3.dtype)

### astype() : dtype을 변환함

In [ ]:
array_int = np.array([1, 2, 3])
print("array_int dtype :",array_int.dtype)
array_float = array_int.astype("float64")
print("array_float dtype :",array_float.dtype)
print("-" * 50)
array_int2 = array_float.astype("int32")
print("array_int2 dtype :",array_int2.dtype)

array_float2 = np.array([1., 2., 3.])
array_float2 = np.array([1.0, 2.0, 3.0])
print("array_float2       :",array_float2)
print("array_float2 dtype :",array_float2.dtype)
array_int3 = array_float2.astype("int32")
print("array_int3       :",array_int3)
print("array_int3 dtype :",array_int3.dtype)

### ndarray 연산 : axis 기반
* axis=0 : 축이 행 - 열끼리 연산함
* axis=1 : 축이 열 - 행 안에 있는 요소들끼리 연산함

In [ ]:
array2 = np.array([
                   [1, 2, 3],
                   [4, 5, 6]
                 ])

print("array2.sum() ;",array2.sum())
print("array2.sum(axis=0) ;",array2.sum(axis=0))
print("array2.sum(axis=1) ;",array2.sum(axis=1))

### ndarray : arange, zeros, ones

In [ ]:
squence_array = np.arange(10)
print("squence_array :",squence_array)
print("squence_array :",type(squence_array))
print("squence_array.dtype :",squence_array.dtype)

In [ ]:
zero_array = np.zeros((3, 2), dtype="int32")
print("zero_array :",zero_array)
print("zero_array :",type(zero_array))
print("zero_array.dtype :",zero_array.dtype)

In [ ]:
one_array = np.ones((3, 2), dtype="int32")
print("one_array :",one_array)
print("one_array :",type(one_array))
print("one_array.dtype :",one_array.dtype)

### ndarray 의  shape 변형하기 :  reshape()

In [ ]:
array1 = np.arange(10)
print("array1 :\n",array1)
array2 = array1.reshape(2, 5)
print("array2 :\n",array2)
array3 = array1.reshape(5, 2)
print("array3 :\n",array3)

# 행과 열의 크기를 data 개수에 맞게 지정해야 함
# ValueError: cannot reshape array of size 10 into shape (3,3)
# array4 = array1.reshape(3, 3)
# print("array4 :\n",array4)

### reshape() 메소드에 -1 을 넣어서 변환하기
* 행의 크기를 고정하고 열의 크기는 자동으로 결정되게 하기
* 열의 크기를 고정하고 행의 크기는 자동으로 결정되게 하기

In [ ]:
array1 = np.arange(10)
print("array1 :\n",array1)

In [ ]:
# 열의 크기를 5로 고정하고 행의 크기는 이에 맞추어서 결정됨
array2 = array1.reshape(-1, 5)
print("array2 :",array2.shape)
print("array2 :\n",array2)

In [ ]:
# 행의 크기를 5로 고정하고 열의 크기는 이에 맞추어서 결정됨
array3 = array1.reshape(5, -1)
print("array3 :",array3.shape)
print("array3 :\n",array3)

In [ ]:
array1 = np.arange(5)
print("array1 :",array1.shape)
print("array1 :\n",array1)
print("-" * 40)

# 1차원 ndarray -> 2차원 ndarray
# 열 axis 의 크기는 1로 함
array2d = array1.reshape(-1, 1)
print("array2d :",array2d.shape)
print("array2d :\n",array2d)
print("-" * 40)

# 2차원 ndarray -> 1차원 ndarray
array1d = array2d.reshape(-1,)
print("array1d :",array1d.shape)
print("array1d :\n",array1d)

In [ ]:
# reshape()에 -1 은 열에 지정하든지, 행에 지정하든지 
# 한 군데에만 지정할 수 있음
# ValueError: can only specify one unknown dimension
# array1.reshape(-1, -1)

### ndarray 에서 data set 선택하기 : indexing
* 특정 위치에 있는 값 추출하기

In [ ]:
array1 = np.arange(1, 10)
print("array1 :",array1.shape)
print("array1 :\n",array1)
print("-" * 40)

value = array1[2]
print("value :",value)
print("value :",type(value))
print("-" * 40)

value = array1[-1]
print("value :",value)
print("value :",type(value))
print("-" * 40)

value = array1[-2]
print("value :",value)
print("value :",type(value))
print("-" * 40)

array1[8] = 0
array1[0] = 9
print("array1 :",array1.shape)
print("array1 :\n",array1)
print("-" * 40)

In [ ]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print("array2d :",array2d.shape)
print("array2d :\n",array2d)
print("-" * 40)

print("array2d[0,0] :",array2d[0,0])
print("array2d[0,1] :",array2d[0,1])
print("array2d[1,0] :",array2d[1,0])
print("array2d[2,2] :",array2d[2,2])

### Slicing

In [ ]:
array1 = np.arange(1, 10)
print("array1 :",array1.shape)
print("array1 :\n",type(array1))
print("array1 :\n",array1)
print("-" * 40)

array2 = array1[0:3]
print("array2 :",array2.shape)
print("array2 :\n",type(array2))
print("array2 :\n",array2)
print("-" * 40)

array3 = array1[:3]
print("array3 :",array3.shape)
print("array3 :\n",type(array3))
print("array3 :\n",array3)
print("-" * 40)

array4 = array1[3:]
print("array4 :",array4.shape)
print("array4 :\n",type(array4))
print("array4 :\n",array4)
print("-" * 40)

array5 = array1[:]
print("array5 :",array5.shape)
print("array5 :\n",type(array5))
print("array5 :\n",array5)
print("-" * 40)

In [ ]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print("array2d :",array2d.shape)
print("array2d :\n",type(array2d))
print("array2d :\n",array2d)
print("=" * 40)

# 1, 2 행 X 1, 2 열
print("array2d[0:2, 0:2] :\n",array2d[0:2, 0:2])
print("-" * 40)
# 1, 2 행 X 1, 2, 3 열
print("array2d[1:3, 0:3] :\n",array2d[1:3, 0:3])
print("-" * 40)
# 1, 2 행 X 1, 2, 3 열 : 시작과 끝을 생략하면 처음부터 끝까지
print("array2d[1:3, :] :\n",array2d[1:3, :])
print("array2d[1:3, 0:3] :\n",array2d[1:3, 0:3])
print("-" * 40)
# 1, 2, 3 행 X 1, 2, 3 열 : 시작과 끝을 생략하면 처음부터 끝까지
print("array2d[:, :] :\n",array2d[:, :])
print("array2d[0:3, 0:3] :\n",array2d[0:3, 0:3])
print("-" * 40)
# 1, 2 행 X 2, 3 열
print("array2d[:2, 1:] :\n",array2d[:2, 1:])
print("array2d[0:2, 1:3] :\n",array2d[:2, 1:])
print("-" * 40)
# 1, 2 행 X 1 열
print("array2d[:2, 0] :\n",array2d[:2, 0])
print("array2d[0:2, 0] :\n",array2d[0:2, 0])
print("-" * 40)

In [ ]:
import numpy as np
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
# array2d = nd.array([[1,2,3],[4,5,6],[7,8,9]])
print("array2d :",array2d.shape)
print("array2d :\n",type(array2d))
print("array2d :\n",array2d)
print("-" * 40)

In [ ]:
# 1 행 2 열 : [0,1]
print(array2d[0,1])

In [ ]:
# 2열
print(array2d[:,1])

In [ ]:
print(array2d[2:,1])

In [ ]:
# 두 번째 열의 첫 번째 부터 두 번째까지
print(array2d[:2,1])

In [ ]:
# 세 번째 행에서 첫 번째 세 번째 요소
print(array2d[2, [0,2]])

In [ ]:
print(array2d > 3)

In [ ]:
print(array2d[array2d > 3])

In [ ]:
array2d[1,1] = 555
print("array2d :\n",array2d)

In [ ]:
# 속도가 빠름
print("array2d[1,1] :",array2d[1,1])
# 속도가 느림
print("array2d[1][1] :",array2d[1][1])

In [ ]:
print("array2d[2, 1:3] :",array2d[2, 1:3])

In [ ]:
print("array2d[:2, 1:3] :",array2d[2, 1:3])

### tolist() : ndarray 를 list 로 변환함
*  array2d[[0,1],2] : fancy indexing

In [ ]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print("array2d :\n",array2d)

array3 = array2d[[0,1],2]
print("array2d[[0,1],2] :\n",array2d[[0,1],2])
print("array3 :\n",array3)
list_array3 = array3.tolist()
print("list_array3 :",list_array3)
print("list_array3 :",type(list_array3))

array4 = array2d[[0,2], 0:2]
print("array2d[[0,2], 0:2] :\n",array2d[[0,2], 0:2])
print("array4 :\n",array4)
print("array4.tolist() :\n",array4.tolist())

array5 = array2d[[0,1]]
print("array2d[[0,1]] :\n",array2d[[0,1]])
print("array5 :\n",array5)
print("array5.tolist() :\n",array5.tolist())

### Boolean Indexing

In [ ]:
array1d = np.arange(1, 10)
print("array1d :\n",array1d)

In [ ]:
print(array1d > 5)

In [ ]:
result = array1d > 5
print("result :\n",result)
print("result :\n",type(result))

In [ ]:
print("array1d[array1d > 5] :\n",array1d[array1d > 5])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
print("array1d[boolean_indexes] :\n",array1d[boolean_indexes])

In [ ]:
# array1d 의 inde 로 이루어진 list 생성하기
#  ㄴ 이것을 ndarray 로 변환하기 (np.array())
array_indexes = np.array([5, 6, 7, 8])
print("array1d[array_indexes] :\n",array1d[array_indexes])

array_indexes2 = np.array([3, 4, 5, 6])
print("array1d[array_indexes2] :\n",array1d[array_indexes2])

In [ ]:
array1d = np.arange(1, 10)
print("array1d :\n",array1d)

list_boolean_filtering = []

for i in range(0, 9):
    # 6, 7, 8, 9
    if array1d[i] > 5:
        list_boolean_filtering.append(array1d[i])
print("list_boolean_filtering :\n",list_boolean_filtering)        

array_boolean_filtering = np.array(list_boolean_filtering)
print("array_boolean_filtering :\n",array_boolean_filtering)

### np.sort() 함수 / ndarray.sort() 메소드 / ndarray.argsort() 메소드
* 행렬 정렬

In [ ]:
origin_array = np.array([3, 1, 5, 9])
print("원본행렬 :\n",origin_array)
print("원본행렬 타입 :\n",type(origin_array))

In [ ]:
# np.sort() 로 정렬하기 - 원본이 변형되지 않음
# 기본 python의 sorted() 함수가 정렬된 새로운 list를 반환한는 것 처럼 
# np.sort() 함수는 정렬된 새로운 ndarray를 반환함
sort_array = np.sort(origin_array)
print("sort_array :\n",sort_array)
print("npl.sort() : 원본이 변형되지 않음")
print("원본행렬 :\n",origin_array)

In [ ]:
# ndarray.argsort() : 원본행렬을 정렬해서 원본요소의 index 를 배치함
#                     원본 행렬의 index를 정렬된 상태에서 배치함
argsort_array = origin_array.argsort()
print("origin_array(원본행렬)의 index 번호가 출력됨")
print("argsort_array :\n",argsort_array)
print("-" * 40)
'''
원본행렬 :
 [3 1 5 9]
sort_array(정렬된 행렬) :
 [1 3 5 9]
argsort_array(원본 행렬의 index를 정렬된 상태에서 출력함) :
 [1 0 2 3]
'''

# ndarray 의 sort() 메소드
# 원본자체를 정렬하고 새로운 ndarray를 생성(반환)하지 않음
sort_array2 = origin_array.sort()
print("sort_array2 :\n",sort_array2)
print("원본행렬이 정렬됨")
print("origin_array :\n",origin_array)

In [ ]:
origin_array = np.array([3, 1, 5, 9])
print("원본행렬(정렬 전) :\n",origin_array)
print("원본행렬 타입 :\n",type(origin_array))

In [ ]:
sort_array = np.sort(origin_array)
print("sort_array :\n",sort_array)

In [ ]:
print("원본행렬(np.sort()로 정렬 후) - 변함없음 :\n",origin_array)

In [ ]:
sort_indexes = np.argsort(origin_array)
print("원본행렬(np.argsort() 실행 후) - 변함없음 :\n",origin_array)
print("원본행렬의 요소들이 정렬되지는 않고 정렬된 원소들의 index가 배치됨")
print("sort_indexes :\n",sort_indexes)
'''
원본                       : [3 1 5 9]
원본의 index               : [0 1 2 3]
정렬                       : [1 3 5 9]
정렬되기 전의 원본의 index : [1 0 2 3]
sort_indexes :
 [1 0 2 3]    <-- [1, 3, 5, 9] 정렬되기 전의 index가 정렬된 상태로 배치됨
'''

### slicing (step) [::-1] 을 활용해서 np.sort() 함수로 내림차순정렬하기

In [ ]:
origin_array = np.array([3, 1, 5, 9])
print("origin_array :\n",origin_array)

sort_array_descending = np.sort(origin_array)[::-1]
print("내림차순 정렬 :\n",sort_array_descending)
print("원본행렬이 변형되지 않음")
print("origin_array :\n",origin_array)

In [ ]:
# 원본 요소들을 내림차순 정렬하기 - [9 5 3 1]
sort_array_descending = np.sort(origin_array)[::-1]
print("sort_array_descending :\n",sort_array_descending)

# 정렬된 상태의 요소들의 (정렬되기 전의) index 들이 배치됨
sort_indexes_descending = np.argsort(origin_array)[::-1]
print("sort_indexes_descending :\n",sort_indexes_descending)

print("원본행렬이 변형되지 않음")
print("origin_array :\n",origin_array)

### 행(row)방향으로 정렬하기 / 열(column)방향으로 정렬하기

In [ ]:
array2d = np.array([
                    [8, 12],
                    [7, 1]
                  ])
print("array2d :",array2d.shape)
print("array2d :\n",type(array2d))
print("array2d :\n",array2d)
print()
print("-- axis=0 : 축이 행 -  row 방향으로 정렬하기 --")
row_array2d = np.sort(array2d, axis=0)
print("row_array2d :\n",row_array2d)
print()
print("-- axis=1 : 축이 열 - column 방향으로 정렬하기 --")
col_array2d = np.sort(array2d, axis=1)
print("col_array2d :\n",col_array2d)

### key-value 형태의 data를 이순신=80, 강감찬=76, 안중근=92, 유관순=56, <br>장보고=70 을 ndarray 로 생성하고 argsort()를 호출해서 key값 정렬하기

In [81]:
name_array   = np.array(["이순신", "강감찬", "안중근", "유관순", "장보고"])
weight_array = np.array([80, 76, 92, 56, 70])

print("name_array :\n",name_array)
print("weight_array :\n",weight_array)
print("-" * 50)


# weight_array 의 정렬된 값에 해당하는 원본 행렬 위치 index를 반환하고
# 이것을 사용해서 name_array에서 name값 추출하기
sort_weight = np.sort(weight_array)
print("sort_weight :\n",sort_weight)
sort_indexes_weight = np.argsort(weight_array)
print("sort_indexes_weight :\n",sort_indexes_weight)

print("몸무게의 오름차순 순으로 이름 정렬하기")
sort_name_by_weight = name_array[sort_indexes_weight]
print("몸무게의 오름차순 순으로 정렬된 이름 :\n",sort_name_by_weight)
print("-" * 50)

print("몸무게의 오름차순 순으로 몸무게 정렬하기")
sort_weight_by_weight = weight_array[sort_indexes_weight]
print("몸무게의 오름차순 순으로 정렬된 몸무게 :\n",sort_weight_by_weight)

name_array :
 ['이순신' '강감찬' '안중근' '유관순' '장보고']
weight_array :
 [80 76 92 56 70]
--------------------------------------------------
sort_weight :
 [56 70 76 80 92]
sort_indexes_weight :
 [3 4 1 0 2]
몸무게의 오름차순 순으로 이름 정렬하기
몸무게의 오름차순 순으로 정렬된 이름 :
 ['유관순' '장보고' '강감찬' '이순신' '안중근']
--------------------------------------------------
몸무게의 오름차순 순으로 몸무게 정렬하기
몸무게의 오름차순 순으로 정렬된 몸무게 :
 [56 70 76 80 92]


### 행렬의 내적과 전치행렬
* 행렬의 내적 : np.dot() 함수 사용

In [82]:
A = np.array([
               [1, 2, 3],
               [4, 5, 6]
             ])
B = np.array([
               [7, 8],
               [9, 10],
               [11, 12] 
             ])
print("A :\n",A)
print("B :\n",B)

A :
 [[1 2 3]
 [4 5 6]]
B :
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [84]:
product_array = np.dot(A, B)
print("product_array(행렬의 내적) :\n",product_array)

product_array(행렬의 내적) :
 [[ 58  64]
 [139 154]]


* 전치 행렬 : np.transpose() 함수 사용

In [85]:
C = np.array([[2, 3],
              [5, 0],
              [1, 1]    
             ])
transpose_matrix1 = np.transpose(C)
print("C 의 전치행렬 :\n",transpose_matrix1)

C 의 전치행렬 :
 [[2 5 1]
 [3 0 1]]


In [87]:
D = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
             ])
transpose_matrix2 = np.transpose(D)
print("D 의 전치행렬 :\n",transpose_matrix2)

D 의 전치행렬 :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [88]:
E = np.array([[1, 2],
              [3, 4],
              [5, 6]    
             ])
transpose_matrix3 = np.transpose(E)
print("E 의 전치행렬 :\n",transpose_matrix3)

E 의 전치행렬 :
 [[1 3 5]
 [2 4 6]]
